version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/fleet-argocd-plugin"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "gomod"
    directory: "/argocd-clusterprofile-syncer"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
