steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$LOCATION-docker.pkg.dev/$PROJECT_ID/infrastructure/docker-credential-gcr:2.1.22'
      - '-t'
      - '$LOCATION-docker.pkg.dev/$PROJECT_ID/infrastructure/docker-credential-gcr:latest'
      - '--file=./Dockerfile'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '$LOCATION-docker.pkg.dev/$PROJECT_ID/infrastructure/docker-credential-gcr'
images:
  - '$LOCATION-docker.pkg.dev/$PROJECT_ID/infrastructure/docker-credential-gcr:2.1.22'
  - '$LOCATION-docker.pkg.dev/$PROJECT_ID/infrastructure/docker-credential-gcr:latest'
